import { analyzeEvent } from '../policy/engine.js';
import { collectAttackLogs } from './collector.js';
import { compareRule } from './comparator.js';
import { proposeRules } from './generator.js';
import { proposeRulesWithInference } from './inference.js';
import { saveShadowRules, shadowStatus } from './shadow.js';
import { learnPaths, readJson, writeJson } from './store.js';
import { learnStatus, shouldAnalyze } from './trigger.js';
import { approveRule, rejectRule } from './updater.js';

function candidateFor(proposal) {
  return {
    id: proposal.id,
    status: proposal.status,
    priority: proposal.rule.severity,
    falsePositiveRisk: proposal.metrics.false_positive === 0 ? 'low' : 'medium',
    needsHumanApproval: true,
    reason: `Learned from ${proposal.evidenceCount} ${proposal.layer} event(s).`,
    rule: proposal.rule,
    metrics: proposal.metrics,
    reviewNotes: [
      'Generated by self-healing analysis from recent warn/block events.',
      'Shadow mode records would-block only; it does not change runtime decisions.',
      'Approve manually before applying to active policy.'
    ],
    evidence: proposal.evidence
  };
}

export async function status(config = {}) {
  return learnStatus(config);
}

export async function analyze(config = {}, { manual = false, windowMinutes } = {}) {
  const currentStatus = await learnStatus(config);
  if (!shouldAnalyze(currentStatus, { manual })) {
    return {
      ok: true,
      analyzed: false,
      reason: `Trigger not ready: ${currentStatus.events}/${currentStatus.minEvents} events and ${currentStatus.highSeverity} high severity events.`,
      status: currentStatus
    };
  }

  const paths = learnPaths(config);
  const attacks = await collectAttackLogs(config, { windowMinutes });
  const rejected = await readJson(paths.rejectedRules, { rules: [] });
  const weights = config.learn?.weights ?? { block_rate: 0.6, false_positive: 0.4 };

  let inference = { source: 'deterministic', skipped: true, reason: 'not_attempted' };
  let baseProposals = [];
  try {
    const result = await proposeRulesWithInference(attacks.attacks, config, { rejectedRules: rejected.rules ?? [] });
    inference = {
      source: result.proposals.length > 0 ? 'openai' : 'deterministic',
      skipped: result.skipped,
      reason: result.reason,
      model: result.model,
      candidateCount: result.candidateCount,
      validCandidates: result.validCandidates
    };
    baseProposals = result.proposals;
  } catch (error) {
    inference = {
      source: 'deterministic',
      skipped: true,
      reason: error.message
    };
  }

  if (baseProposals.length === 0) {
    baseProposals = proposeRules(attacks.attacks, { rejectedRules: rejected.rules ?? [] });
  }

  const proposals = baseProposals
    .map((proposal) => ({
      ...proposal,
      metrics: compareRule(proposal, weights),
      status: 'shadow'
    }));

  const output = {
    generatedAt: new Date().toISOString(),
    rules: proposals
  };
  await writeJson(paths.pendingRules, output);
  await saveShadowRules(proposals, config);
  await writeJson(paths.samples, {
    generatedAt: output.generatedAt,
    samples: proposals.map((proposal) => ({
      id: proposal.id,
      samples: proposal.samples
    }))
  });
  await writeJson(paths.ruleCandidates, {
    generatedAt: output.generatedAt,
    source: paths.attackLogs,
    candidates: proposals.map(candidateFor)
  });

  return {
    ok: true,
    analyzed: true,
    attacks: attacks.count,
    proposed: proposals.length,
    shadowRules: proposals.length,
    inference,
    paths: {
      attackLogs: paths.attackLogs,
      pendingRules: paths.pendingRules,
      shadowRules: paths.shadowRules,
      ruleCandidates: paths.ruleCandidates
    }
  };
}

export async function pending(config = {}) {
  return readJson(learnPaths(config).pendingRules, { rules: [] });
}

export async function testRule(id, config = {}) {
  const pendingRules = await pending(config);
  const entry = (pendingRules.rules ?? []).find((rule) => rule.id === id);
  if (!entry) {
    throw new Error(`Unknown pending rule: ${id}`);
  }
  return {
    id,
    metrics: compareRule(entry, config.learn?.weights ?? { block_rate: 0.6, false_positive: 0.4 }),
    attacks: (entry.samples?.attacks ?? []).map((sample) => ({
      sample,
      decision: analyzeEvent({ type: entry.rule.appliesTo[0], text: sample }, { rules: [entry.rule] }).decision
    })),
    near_miss_benign: (entry.samples?.near_miss_benign ?? []).map((sample) => ({
      sample,
      decision: analyzeEvent({ type: entry.rule.appliesTo[0], text: sample }, { rules: [entry.rule] }).decision
    }))
  };
}

export { approveRule, rejectRule, shadowStatus };
